Repository nicorithner/chinese-menu-generator-be, pull requests merged in 2023-07, with the labels that each got.

#37 Update menu
  .eslintrc.js
  package-lock.json
  package.json
  src/controllers/menu.controller.ts
Labels: API

#40 add column type to string types
  src/app.js
  src/config/config.js
  src/models/ingredient.entity.js
  src/models/ingredient.entity.ts
  src/models/menu.entity.js
  src/models/menu.entity.ts
  src/models/recipe.entity.js
  src/models/recipe.entity.ts
  src/models/user.entity.js
  src/models/user.entity.ts
  src/server.js
Labels: bug, Lingling, Nico, Database

#42 Update the recipe tests
  __tests__/routes/recipes.test.ts
Labels: Lingling, API, Tests

#44 Add a new ERD file to asset
  assets/Updated ERD.png
Labels: documentation, Lingling

#43 Update swagger
  src/routes/menu.routes.ts
  src/routes/recipe.routes.ts
  src/routes/user.routes.ts
Labels: documentation, Lingling

#45 Update readme with project description
  README.md
Labels: documentation, Nico
